# Define a custom port instead of the default 8080
server:
  port: 8091
  servlet:
    contextPath: /modulestockage
  tomcat:
    accesslog:
      enabled: true
    basedir: /home/tomcat/avp_spring

spring:
  main:
    banner-mode: 'off'

app:
  storagePath: /home/tomcat/storage
  maxCheckFilesByThread: 10