# Define a custom port instead of the default 8080
server:
  port: 8088
  servlet:
    contextPath: /modulestockage
  tomcat:
    accesslog:
      enabled: true
    basedir: /home/tomcat/tomcat

spring:
  main:
    banner-mode: 'off'

app:
  storagePath: C:/Dev/storage
  maxCheckFilesByThread: 10